management:
  endpoints:
    web:
      exposure:
        include: '*'

# H2 connection
spring:
  application:
    name: spring-boot-kotlin-microservice
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    database-platform: org.hibernate.dialect.H2Dialect

url:
  products: "http://localhost:8080/"

keycloak:
  realm: example
  resource: spring-boot
  bearer-only: true
  auth-server-url: http://localhost:8090/auth

logging:
  file:
    name: example.log